CREATE USER ACCOUNT
    IDENTIFIED BY account
    DEFAULT TABLESPACE "USERS"
    TEMPORARY TABLESPACE "TEMP"
    QUOTA 100M ON "USERS";

GRANT CONNECT TO ACCOUNT;

GRANT CREATE TABLE TO ACCOUNT;
GRANT CREATE SEQUENCE TO ACCOUNT;
GRANT CREATE TRIGGER TO ACCOUNT;
GRANT SELECT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE, INSERT ANY TABLE TO ACCOUNT;